### ISSUE TITLE
授業名でシラバスを検索するAPIの実装

### ISSUE THREAD

**Issue by Atotti** [gdsc-tmu/InfoLinkAPI#2]
授業名でシラバスを検索するAPIの設計と実装をする。
部分一致やLIKE等いろいろな方法があるが、良さそうなのを試して実装する。

設計ではエンドポイントとレスポンスモデルを決めて、notionのデータベースにドキュメントとして残してください。

**Comment by taniiicom** [comment]
if needed
- meilisearch, elasticsearch など

**Comment by Atotti** [comment]
一応、
検索エンジンの導入は別Issue立てた方が良くて、ここは単純にSQLで検索で良いと思います。
