### ISSUE TITLE
Open APIのドキュメントの更新忘れ

### ISSUE THREAD

**Issue by Atotti** [gdsc-tmu/InfoLinkAPI#31]
@tenk-9 

`faculies` → `faculty`の更新がOpenAPIの定義(Swagger doc)に反映されていない気がします。

localhost:8080/swagger/index.html からのAPIの実行が正常に動いているでしょうか？
おそらく`swag init`とかその辺のコマンド実行すればコードに合わせて自動で更新されるはずです。

https://github.com/gdsc-tmu/InfoLinkAPI/blob/4371d518ebdaf729af10228249cae22ed12162d9/docs/swagger.yaml#L45-L69

**Comment by tenk-9** [comment]
うおーごめんなさい、その通りで、swag initしていないです、すぐ直します

**Comment by Atotti** [comment]
急ぎではないので大丈夫です！
